src/enverest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('homepage.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r"^account/", include("account.urls")),
    url(r"^consultant/", include("consultant.urls")),
    url(r"^search/", include("search.urls")),
    url(r"^project/", include("project.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include("userprofile.urls")),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^payment/', include('payment.urls', namespace='payment', app_name='payment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/project/urls.py
from django.conf.urls import url

from . import views

app_name = 'project'
urlpatterns = [
    url(r'^create$', views.create, name='create'),
    url(r'^expertchoice$', views.expertchoice, name='expertchoice'),
    url(r'^expertstart$', views.expertstart, name='expertstart'),
    url(r'^expertworking$', views.expertworking, name='expertworking'),
    url(r'^clientchoice$', views.clientchoice, name='clientchoice'),
    url(r'^clientconfirm$', views.clientconfirm, name='clientconfirm'),
    url(r'^waitassignexpert$', views.waitassignexpert, name='waitassignexpert'),
    url(r'^waitclientconfirm$', views.waitclientconfirm, name='waitclientconfirm'),
    url(r'^waitexpertstart$', views.waitexpertstart, name='waitexpertstart'),
    url(r'^waitexpertworking$', views.waitexpertworking, name='waitexpertworking'),
    url(r'^waitpayment$', views.waitpayment, name='waitpayment'),
    url(r'^rate$', views.rate, name='rate'),
    url(r'^close$', views.close, name='close'),
    url(r'^thanks$', views.thanks, name='thanks'),
    url(r'^unavailable$', views.unavailable, name='unavailable'),
    url(r'^upload$', views.upload, name='upload'),
    url(r'^showupload$', views.showupload, name='showupload'),
    url(r'^clientonly$', views.clientonly, name='clientonly'),
]

src/search/urls.py
from django.conf.urls import url

#from . import views
from search.views import ExpertDetailView, ExpertListView

app_name = 'search'
urlpatterns = [
    #url(r'^$', views.index, name='index'),
    #url(r'^$', ExpertListView.as_view(), name='expert-list'),
    url(r'^$', ExpertListView.as_view(), name='expert-list'),
    url(r'^(?P<pk>[\w]+)/detail$', ExpertDetailView.as_view(), name='expert-detail'),
    #url(r'^search/(?P<lastname>.+)$', ExpertListView.as_view(), name='expert-list'),
]

src/project/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from datetime import date
from common.models import Client, Expert, ProjectFile

INDUSTRY_CHOICES = (
    ("MC","Management Consulting"),
    ("EN","Energy"),
    ("HI","Health care and Life Sciences"),
    ("BI","BioPharma"),
    ("ED","Education"),
    ("SE","Semiconductor"),
    ("SW","Software"),
    ("MB","Mobile Internet and Computing"),
    ("DS","Data and Storage"),
    ("VR","VR/AI/Robotics"),
    ("IT","Internet of Things"),
    ("GB","Gaming and Media"),
    ("ET","Entertainment"),
    ("TL","Transport and Logistics"),
    ("AU","Automotive"),
    ("CG","Consumer Goods"),
    ("OT","Others"),
)

EXPERTISE_CHOICES = (
    ("ST","Strategy"),
    ("BD","Business Development and Sales"),
    ("SP","Strategic Partnership"),
    ("MK","Marketing"),
    ("MT","Market Research"),
    ("OS","Operations and Supply Chain"),
    ("MA","Merger and Acquisition"),
    ("DA","Data Analytics"),
    ("SE","Software Engineering"),
    ("PJ","Project Management"),
    ("PD","Product Design and Development"),
    ("PM","Product Management"),
    ("EN","Entrepreneurship"),
    ("CC","Cloud Computing"),
    ("AD","Advertisement"),
    ("CL","Corporate Law"),
    ("CF","Corporate Finance"),
    ("AT","Accounting and Taxation"),
    ("OT","Others"),
)

DEEP_DIVE = 'D'
GENERAL_ADVISORY = 'G'

SERVICE_CHOICES = (
   (DEEP_DIVE, 'Deep dive'),
   (GENERAL_ADVISORY, 'General advisory'),
)

FIXED = 'F'
HOURLY = 'H'

RATING_CHOICES = (
    (FIXED, 'Fixed amount'),
    (HOURLY, 'Hourly rate'),
)
class ProjectForm(forms.Form):
    project_name = forms.CharField(label=_('Name'), max_length=200,
                                   widget=forms.TextInput(
                                   	    attrs={'placeholder':_('Give your engagement request a name'),
                                   	           'size':'60'}))
    project_description = forms.CharField(label=_('Description'), max_length=10000,
                                           widget=forms.Textarea(
                                   	         attrs={'placeholder':_('Describe what needs to be done for the engagement'),
                                                    'rows':10,
                                                    'cols':59}))
    project_expert_industry = forms.ChoiceField(label=_('Expert Industry'), choices=INDUSTRY_CHOICES, required=True)
    project_expert_expertise = forms.ChoiceField(label=_('Expert Expertise'), choices=EXPERTISE_CHOICES, required=True)
    project_expert_preference = forms.CharField(label=_('Expert Preference'), max_length=1000,
                                           widget=forms.Textarea(
                                   	         attrs={'placeholder':_('Describe what kind of expert do you want to work with'),
                                                    'rows':4,
                                                    'cols':59}))
    project_pub_date = forms.DateTimeField(label=_('Start Date'), input_formats=['%Y-%m-%d'],
                                           widget=forms.TextInput(
                                              attrs={'placeholder':'YYYY-mm-dd',
                                                      'size':'60',
                                                      'class': 'datepicker'
                                                      }))
    project_end_date = forms.DateTimeField(label=_('Due Date'), input_formats=['%Y-%m-%d'],
                                            widget=forms.TextInput(
                                              attrs={'placeholder':'YYYY-mm-dd',
                                                      'size':'60',
                                                      'class': 'datepicker'
                                                      }))
    project_service_type = forms.ChoiceField(
        label=mark_safe('Service Type (<a href="/how_it_works/#faq" target="_blank">FAQ</a>)'),
        choices=SERVICE_CHOICES,
        required=True
    )
    project_rate_type = forms.ChoiceField(
      label=mark_safe('Rate Type (<a href="/how_it_works/#faq" target="_blank">FAQ</a>)'),
      choices=RATING_CHOICES,
      required=True)
    project_rate = forms.DecimalField(label=_('Budget'), max_digits=8, decimal_places=2,
    	                                    widget=forms.TextInput(
                                              attrs={'placeholder':_('In dollars or hours'),
                                                     'size':'60'}))
class ProjectFileForm(ModelForm):

  class Meta:
    model = ProjectFile
    fields = ['avatar']
    labels = {
        'avatar':'',
    }

src/project/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from common.models import Project,Client,Expert,CommentForExpert,CommentForClient, ProjectFile

from .forms import ProjectForm ,ProjectFileForm
import logging

logger = logging.getLogger(__name__)

state_message_option = {
    'ept_a':'The client will review it and get back to you',
    'ept_f':'The client will review your work and get back to you',
    'ept_s':'Thank you for working on this engagement and the client will be notified soon',
    'clt_s':'We will review your engagement and an expert will be assigned to you soon',
    'clt_c':'You will receive the contract and payment information soon',
    'clt_n':'The expert will keep working on the engagement',
    'clt_y':'The engagement is now finished',
    'clt_a':'An administrator will contact you soon',
    'ept_rating':'Your rating will help us improve',
    'clt_rating':'Your rating will help us improve',
}

def getCurrentRole(request):
    User = get_user_model()
    if request.user.id == None:
      return False
    user_id = request.user.id
    profile_user = User.objects.get(pk=user_id)
    user_profiles = profile_user.userprofile_set.all()
    user_profile = None
    if user_profiles:
        user_profile = user_profiles[0]
    else:
        return None
    person = None
    is_expert = None
    if user_profile.user_type == 'CLIENT':
        is_expert = False
        clients = profile_user.client_set.all()
        person = clients[0]
    elif user_profile.user_type == 'EXPERT':
        is_expert = True
        experts = profile_user.expert_set.all()
        person = experts[0]
    return person

def hasPermission(request, project, require_expert):
    User = get_user_model()
    if request.user.id == None or project == None:
      return False
    user_id = request.user.id
    profile_user = User.objects.get(pk=user_id)
    user_profiles = profile_user.userprofile_set.all()
    #
    user_profile = None
    if user_profiles:
        user_profile = user_profiles[0]
    else:
    #   raise ObjectDoesNotExist("user doesn't assoicate with any user_profile.")
         return False
    person = None
    is_expert = None

    if user_profile.user_type == 'CLIENT':
        if require_expert == True:
          return False
        clients = profile_user.client_set.all()
        person = clients[0]
        if person != project.client:
            return False
    elif user_profile.user_type == 'EXPERT':
        if require_expert == False:
          return False
        experts = profile_user.expert_set.all()
        person = experts[0]
        if person != project.expert:
            return False
    else:
        return False
    #    raise ObjectDoesNotExist("user doesn't assoicate with any client/expert.")
    return True

#Check if the current role in the request: 
#client return True, expert return False; no such user return None
def isClient(request):
    User = get_user_model()
    if request.user.id == None:
      return None
    user_id = request.user.id
    profile_user = User.objects.get(pk=user_id)
    user_profiles = profile_user.userprofile_set.all()
    #
    user_profile = None
    if user_profiles:
        user_profile = user_profiles[0]
    else:
        return None
    if user_profile.user_type == 'CLIENT':
      return True
    return False

#This is the utility function for post method, it checks the permission and
#if it has the permission it will get the project from the db and return,
#Otherwise it will return None
def getProjectFromPost(request, expectStatus, require_expert):
    if request.method != 'POST':
      return None
    if 'project_id' not in request.POST:
      return None
    project_id_val = request.POST['project_id']
    project = None
    try:
      project = Project.objects.get(pk=project_id_val)
    except ObjectDoesNotExist:
      print("no object")
      return None
    if(project.state not in expectStatus):
      print(project.state)
      return None
    if hasPermission(request, project, require_expert) == False:
      print("no permission")
      return None
    return project

def create(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        if isClient(request) == False:
          return HttpResponseRedirect('clientonly')
        # create a form instance and populate it with data from the request:
        form = ProjectForm(request.POST)

        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            new_project = Project(client=getCurrentRole(request),
                                  expert=(Expert.objects.all())[0],
                                  title_text=form.cleaned_data['project_name'],
                                  info_text=form.cleaned_data['project_description'],
                                  expert_pref_text=form.cleaned_data['project_expert_preference'],
                                  pub_date=form.cleaned_data['project_pub_date'],
                                  end_date=form.cleaned_data['project_end_date'],
                                  rate=form.cleaned_data['project_rate'],
                                  assign_history='',
                                  state='PS',
                                  assgin_to='ADM',
                                  industry=form.cleaned_data['project_expert_industry'],
                                  expertise=form.cleaned_data['project_expert_expertise'],
                                  rate_type=form.cleaned_data['project_rate_type'],
                                  service_type=form.cleaned_data['project_service_type'],
                )
            new_project.save()
            # redirect to a new URL:
            return HttpResponseRedirect('thanks?last_action=clt_s')

    # if a GET (or any other method) we'll create a blank form
    else:
        result = isClient(request)
        if result == False or result ==None:
          return HttpResponseRedirect('clientonly')
        form = ProjectForm(label_suffix=' ')

    return render(request, 'create.html', {'form': form})

def expertchoice(request):
    if request.method == 'GET':
        logger.info("expertchoice GET")
        return generalGetPage(request, 'expertchoice', set(['EA']), True)
    else:
      project = getProjectFromPost(request, set(['EA']), True)
      if project == None:
        return HttpResponseRedirect('unavailable')
      if 'accept_project' not in request.POST:
        return HttpResponseRedirect('unavailable')
      accept_val = request.POST['accept_project']
      if accept_val == 'A':
        project.state = 'ET'
      elif accept_val == 'D':
        project.state = 'PS'
      project.save()
      return HttpResponseRedirect('thanks?last_action=ept_a')


def clientchoice(request):
    if request.method == 'GET':
        return generalGetPage(request, 'clientchoice', set(['ET']), False)
    else:
      project = getProjectFromPost(request, set(['ET']), False)
      if project == None:
        return HttpResponseRedirect('unavailable')
      if 'accept_expert' not in request.POST:
        return HttpResponseRedirect('unavailable')
      accept_val = request.POST['accept_expert']
      if accept_val == 'A':
        project.state = 'CA'
      elif accept_val == 'D':
        project.state = 'PS'
      project.save()
      return HttpResponseRedirect('thanks?last_action=clt_c')

def expertworking(request):
    if request.method == 'GET':
      return generalGetPage(request, 'expertworking', set(['IP']), True)
    else:
      project = getProjectFromPost(request, set(['IP']), True)
      if project == None:
        return HttpResponseRedirect('unavailable')
      project.state = 'PF'
      project.save()
      return HttpResponseRedirect('thanks?last_action=ept_f')

def expertstart(request):
    if request.method == 'GET':
      return generalGetPage(request, 'expertstart', set(['CA']), True)
    else:
      project = getProjectFromPost(request, set(['CA']), True)
      if project == None:
        return HttpResponseRedirect('unavailable')
      project.state = 'IP'
      project.save()
      return HttpResponseRedirect('thanks?last_action=ept_s')

def clientconfirm(request):
    if request.method == 'GET':
      return generalGetPage(request, 'clientconfirm', set(['PF']), False)
    else:
      project = getProjectFromPost(request, set(['PF']), False)
      if project == None:
        return HttpResponseRedirect('unavailable')
      if 'accept_finish' not in request.POST:
        return HttpResponseRedirect('unavailable')
      redirectStr = ''
      confirm_val = request.POST['accept_finish']
      if confirm_val == 'Y': #Accept finish
        project.state = 'CC'
        project.save()
        return HttpResponseRedirect('rate?project_id='+str(project.pk))
      elif confirm_val == 'N': #Need more work
        project.state = 'IP'
        redirectStr = 'clt_n'
      elif confirm_val == 'A': #Cannot make agreement, Appeal
        project.state = 'AD'
        redirectStr = 'clt_a'
      project.save()
      return HttpResponseRedirect('thanks?last_action='+redirectStr)

def waitassignexpert(request):
    return generalGetPage(request, 'waitassignexpert', set(['PS','EA']), False)

def waitclientconfirm(request):
    return generalGetPage(request, 'waitclientconfirm', set(['PF','ET']), True)

def waitexpertstart(request):
    return generalGetPage(request, 'waitexpertstart', set(['CA']), False)

def waitexpertworking(request):
    return generalGetPage(request, 'waitexpertworking',set(['IP']), False)

def waitpayment(request):
    return generalGetPage(request, 'waitpayment',set(['CC']), True)

def rate(request):

src/project/templates/clientchoice.html
{% extends "base_project.html" %}
{% load i18n %}


{% block progress_tracker %}
<div class="progress-container">
  <ol class="progress-meter">
    <li class="progress-point done">{% trans "Expert Accept" %}</li><li class="progress-point todo">Confirm</li><li class="progress-point todo">{% trans "Sign Contract" %}</li><li class="progress-point todo">{% trans "Work on" %}</li><li class="progress-point todo">Finish</li><li class="progress-point todo">{% trans "Payment" %}</li>
  </ol>
</div>
{% endblock %}


{% block choice_content %}
<br>
<a href="/messages/write?id_recipients={{ project.expert.user }}&id_subject={{ project.title_text }}" >{% trans "Write messages to the expert" %}</a>
<p></p>
<p>{% trans "An expert want to work with you on this engagement. Do you accept this expert?" %}</p>
<form id="choiceForm" action="{% url 'project:clientchoice' %}" method="POST">{% csrf_token %}
<div class="dropdown">
<select name="accept_expert">
    <option id="Accept" value="A">{% trans "Accept" %}</option>
    <option id="Decline" value="D">{% trans "Decline" %}</option>
    <option id="NeedInfo" value="N">{% trans "Need More Info" %}</option>
</select>
<button class="pure-button pure-button-primary" type="submit" value="Submit" > {% trans "Submit" %} </button>
</form>

<script>
  function getQueryVariable(variable)
  {
       var query = window.location.search.substring(1);
       var vars = query.split("&");
       for (var i=0;i<vars.length;i++) {
               var pair = vars[i].split("=");
               if(pair[0] == variable){return pair[1];}
       }
       return(false);
  }

  $("#choiceForm").submit( function() {
      $('<input />').attr('type', 'hidden')
          .attr('name', "project_id")
          .attr('value', getQueryVariable("project_id"))
          .appendTo('#choiceForm');
      return true;
  });
</script>

{% endblock %}

src/project/templates/close.html
{% extends "base_project.html" %}
{% load i18n %}

{% block progress_tracker %}
<div class="progress-container">
  <ol class="progress-meter">
    <li class="progress-point done">{" trans "Accept" %}</li><li class="progress-point done">Client Confirm</li><li class="progress-point done">{% trans "Sign Contract" %}</li><li class="progress-point done">Work on</li><li class="progress-point done">{% trans "Finish" %}</li><li class="progress-point done">{% trans "Payment" %}</li>
  </ol>
</div>
{% endblock %}


{% block choice_content %}
<p></p>
<p><b>{% trans "This project is closed" %}<b>.</p>

{% endblock %}

src/project/templates/create.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load bootstrap %}

{% block content %}
<script>
    $(document).ready(function() {
        $('.datepicker').datepicker({minDate: new Date, dateFormat: 'yy-mm-dd'});
    });
</script>

<style>
  span.help-block {
     color: red;
  }
</style>

<div class="container">
    <div class="row">
        <div class="col-sm-3">
        </div>
        <div class="col-sm-6">
            <form class="pure-form pure-form-stacked" action="create" method="post">{% csrf_token %}
                <fieldset>
                <legend> {% trans "Create a new engagement in just a few minutes" %}</legend>
                {% csrf_token %}
                {{ form|bootstrap }}
                <button type="submit" value="Submit" class="pure-button-primary">{% trans "Submit" %}</button>
                </fieldset>
            </form>
        </div>
        <div class="col-sm-3">
        </div>
    </div>
</div> <!-- for Container -->

{% endblock %}

src/project/templates/expertchoice.html
{% extends "base_project.html" %}
{% load i18n %}

{% block progress_tracker %}
<div class="progress-container">
  <ol class="progress-meter">
    <li class="progress-point todo">{% trans "Accept" %}</li><li class="progress-point todo">Client Confirm</li><li class="progress-point todo">{% trans "Sign Contract" %}</li><li class="progress-point todo">Work on</li><li class="progress-point todo">{% trans "Finish" %}</li><li class="progress-point todo">{% trans "Payment" %}</li>
  </ol>
</div>
{% endblock %}


{% block choice_content %}
<p></p>
<p>{% trans "Are you taking this project?" %}</p>
<form id="choiceForm" action="{% url 'project:expertchoice' %}" method="POST">{% csrf_token %}
<div class="dropdown">
<select name="accept_project">
    <option id="Accept" value="A">{% trans "Accept" %}</option>
    <option id="Decline" value="D">{% trans "Decline" %}</option>
    <option id="NeedInfo" value="N">{% trans "Need More Info" %}</option>
</select>
<button class="pure-button pure-button-primary" type="submit" value="Submit" > {% trans "Submit" %} </button>
</form>

<script>
  function getQueryVariable(variable)
  {
       var query = window.location.search.substring(1);
       var vars = query.split("&");
       for (var i=0;i<vars.length;i++) {
               var pair = vars[i].split("=");
               if(pair[0] == variable){return pair[1];}
       }
       return(false);
  }

  $("#choiceForm").submit( function() {
      $('<input />').attr('type', 'hidden')
          .attr('name', "project_id")
          .attr('value', getQueryVariable("project_id"))
          .appendTo('#choiceForm');
      return true;
  });
</script>

{% endblock %}

src/project/templates/expertstart.html
{% extends "base_project.html" %}
{% load staticfiles %}
{% load i18n %}

{% block progress_tracker %}
<div class="progress-container">
  <ol class="progress-meter">
    <li class="progress-point done">{% trans "Accept" %}</li><li class="progress-point done">Client Confirm</li><li class="progress-point done">{% trans "Sign Contract" %}</li><li class="progress-point todo">Work on</li><li class="progress-point todo">{% trans "Finish" %}</li><li class="progress-point todo">{% trans "Payment" %}</li>
  </ol>
</div>
{% endblock %}


{% block choice_content %}
<p></p>
<a href="/messages/write?id_recipients={{ project.client.user }}&id_subject={{ project.title_text }}" >{% trans "Write messages to the client" %}</a>
<p><b>{% blocktrans %}After you received the contract from the client, click "start" button to start working on this project. You can also download{% endblocktrans %} <a href="{% static 'docs/EXPERT_ADVISORY_AGREEMENT_TEMPLATE.docx' %}">{% trans "Expert Advisory Agreement Template" %}</a> {% trans "and" %} <a href="{% static 'docs/TWO_WAY_NDA_TEMPLATE.docx' %}">{% trans "NDA Template" %}</a> {% trans "here" %}.<b></p>
<form id="choiceForm" action="{% url 'project:expertstart' %}" method="POST">{% csrf_token %}
<button class="pure-button pure-button-primary" type="submit" value="Submit" > {% trans "Start" %} </button>
</form>

<script>
  function getQueryVariable(variable)
  {
       var query = window.location.search.substring(1);
       var vars = query.split("&");
       for (var i=0;i<vars.length;i++) {
               var pair = vars[i].split("=");
               if(pair[0] == variable){return pair[1];}
       }
       return(false);
  }

  $("#choiceForm").submit( function() {
      $('<input />').attr('type', 'hidden')
          .attr('name', "project_id")
          .attr('value', getQueryVariable("project_id"))
          .appendTo('#choiceForm');
      return true;
  });
</script>

{% endblock %}

src/project/templates/rateexpert.html
{% extends "base_project.html" %}

{% block progress_tracker %}
<div class="progress-container">
  <ol class="progress-meter">
    <li class="progress-point done">Accept</li><li class="progress-point done">Client Confirm</li><li class="progress-point done">Sign Contract</li><li class="progress-point done">Work on</li><li class="progress-point done">Finish</li><li class="progress-point todo">Payment</li>
  </ol>
</div>
{% endblock %}


{% block choice_content %}
<p></p>

<p></p>
<form class="rating" id="choiceForm" action="{% url 'rateexpert' %}" method="POST">{% csrf_token %}
    <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
    <input type="radio" id="star4half" name="rating" value="4.5" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
    <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
    <input type="radio" id="star3half" name="rating" value="3.5" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
    <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
    <input type="radio" id="star2half" name="rating" value="2.5" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
    <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
    <input type="radio" id="star1half" name="rating" value="1.5" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
    <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
    <input type="radio" id="starhalf" name="rating" value="0.5" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
    <br>
    <textarea name="comment" cols="59" rows="2" placeholder="Write your review here"></textarea>
    <br>
    <button class="pure-button pure-button-primary" type="submit" value="Submit" > Submit </button>
</form>

<script>
  function getQueryVariable(variable)
  {
       var query = window.location.search.substring(1);
       var vars = query.split("&");
       for (var i=0;i<vars.length;i++) {
               var pair = vars[i].split("=");
               if(pair[0] == variable){return pair[1];}
       }
       return(false);
  }

  $("#choiceForm").submit( function() {
      $('<input />').attr('type', 'hidden')
          .attr('name', "project_id")
          .attr('value', getQueryVariable("project_id"))
          .appendTo('#choiceForm');
      return true;
  });
</script>

{% endblock %}

src/project/templates/showupload.html
{% extends "base_project.html" %}
{% load staticfiles %}
{% load i18n %}

{% block progress_tracker %}
<div class="progress-container">
  <ol class="progress-meter">
    <li class="progress-point todo">{% trans "Expert Accept" %}</li><li class="progress-point todo">{% trans "Confirm" %}</li><li class="progress-point todo">{% trans "Sign Contract" %}</li><li class="progress-point todo">{% trans "Work on" %}</li><li class="progress-point todo">{% trans "Finish" %}</li><li class="progress-point todo">{% trans "Payment" %}</li>
  </ol>
</div>
{% endblock %}


{% block choice_content %}
<a href="{% static file.avatar.name %}">{{ file.file_name }}</a>

{% endblock %}

src/project/templates/thanks.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}

<div class="container">
<img src="{% static 'images/thankyou.jpg' %}" style="width:304px;height:228px;" align="middle">
<h5>{% trans "We have received your request" %}</h5>
<h5>{{message_display}}</h5>
{% if last_action == "clt_rating" %}
<a href="/payment">{% trans "Proceed to payment" %}</a>
<br>
{% endif %}
<a href="/consultant/dashboard">{% trans "Back to dash board" %}</a>
</div> <!-- for Container -->

{% endblock %}

src/project/templates/unavailable.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}

<div class="container">
<img src="{% static 'images/page_not_available.jpg' %}" style="width:415px;height:400px;" align="middle">
<h5>{% trans "Sorry, please make sure you entered the correct address" %}</h5>
</div> <!-- for Container -->

{% endblock %}

src/project/templates/waitassignexpert.html
{% extends "base_project.html" %}
{% load i18n %}

{% block progress_tracker %}
<div class="progress-container">
  <ol class="progress-meter">
    <li class="progress-point todo">{% trans "Accept" %}</li><li class="progress-point todo">{% trans "Client Confirm" %}</li><li class="progress-point todo">{% trans "Sign Contract" %}</li><li class="progress-point todo">{% trans "Work on" %}</li><li class="progress-point todo">{% trans "Finish" %}</li><li class="progress-point todo">{% trans "Payment" %}</li>
  </ol>
</div>
{% endblock %}


{% block choice_content %}
<p></p>
<p><b>{% trans "An expert will take this engagement soon" %}<b>.</p>

{% endblock %}