src/enverest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('homepage.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r"^account/", include("account.urls")),
    url(r"^consultant/", include("consultant.urls")),
    url(r"^search/", include("search.urls")),
    url(r"^project/", include("project.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include("userprofile.urls")),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^payment/', include('payment.urls', namespace='payment', app_name='payment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/search/urls.py
from django.conf.urls import url

#from . import views
from search.views import ExpertDetailView, ExpertListView

app_name = 'search'
urlpatterns = [
    #url(r'^$', views.index, name='index'),
    #url(r'^$', ExpertListView.as_view(), name='expert-list'),
    url(r'^$', ExpertListView.as_view(), name='expert-list'),
    url(r'^(?P<pk>[\w]+)/detail$', ExpertDetailView.as_view(), name='expert-detail'),
    #url(r'^search/(?P<lastname>.+)$', ExpertListView.as_view(), name='expert-list'),
]

src/common/models.py
from __future__ import unicode_literals

import datetime
import operator

try:
    from urllib.parse import urlencode
except ImportError:  # python 2
    from urllib import urlencode

from django.core.urlresolvers import reverse
from django.db import models, transaction
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone, translation, six
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import AnonymousUser
from django.contrib.sites.models import Site
from django.core.validators import RegexValidator

import pytz
from common.multichoice import MultiSelectField

from account import signals
from account.conf import settings
from account.fields import TimeZoneField
from account.hooks import hookset
from account.managers import EmailAddressManager, EmailConfirmationManager
from account.signals import signup_code_sent, signup_code_used

import uuid
import os
class UserProfile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    avatar = models.ImageField(_("Avatar"), upload_to='avatar/', blank=True)
    summary = models.CharField("Summary", max_length=500, default="Summary default.")
    CLIENT = 'CLIENT'
    EXPERT = 'EXPERT'
    USER_TYPES = (
       (CLIENT, 'CLIENT'),
       (EXPERT, 'EXPERT')
    )
    user_type = models.CharField(max_length=20,
                                choices=USER_TYPES,
                                default=CLIENT)

    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
    )

    work_phone_number = models.CharField(
        max_length=15,
        validators=[phone_regex],
        blank=True
    )

    cell_phone_number = models.CharField(
        max_length=15,
        validators=[phone_regex],
        blank=True
    )

    title = models.CharField(
        max_length=30,
        blank=True
    )
    company = models.CharField(
        max_length=30,
        blank=True
    )


    country = models.CharField(
        max_length=30,
        blank=True
    )

    state = models.CharField(
        max_length=30,
        blank=True
    )

    city = models.CharField(
        max_length=48,
        blank=True
    )

    street = models.CharField(
        max_length=128,
        blank=True
    )

    zip_code = models.CharField(
        max_length=10,
        blank=True
    )

    @classmethod
    def create(cls, form, request=None, **kwargs):
        profile = cls(**kwargs)
        profile.user = kwargs.pop("user", None)
        if form.cleaned_data['profile_image']:
            profile.avatar = form.cleaned_data['profile_image']
        if form.cleaned_data['work_phone_number']:
            profile.work_phone_number = form.cleaned_data['work_phone_number']
        if form.cleaned_data['cell_phone_number']:
            profile.cell_phone_number = form.cleaned_data['cell_phone_number']
        if form.cleaned_data['title']:
            profile.title = form.cleaned_data['title']
        if form.cleaned_data['company']:
            profile.company = form.cleaned_data['company']
        if form.cleaned_data['country']:
            profile.country = form.cleaned_data['country']
        if form.cleaned_data['state']:
            profile.state = form.cleaned_data['state']
        if form.cleaned_data['city']:
            profile.city = form.cleaned_data['city']
        if form.cleaned_data['street']:
            profile.street = form.cleaned_data['street']
        if form.cleaned_data['zip_code']:
            profile.zip_code = form.cleaned_data['zip_code']
        profile.save()
        return profile

class Client(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    def has_worked_before(self, expert):
      experts = [project.expert for project in Project.objects.filter(client=self)]
      return expert in experts

    @classmethod
    def create(cls, form, request=None, **kwargs):
        client = cls(**kwargs)
        client.user = kwargs.pop("user", None)
        client.save()
        return client

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + "(username:" + self.user.username + ")"

    rating = models.DecimalField(max_digits=3, decimal_places=1, default=0)
    comments_num = models.PositiveIntegerField(default=0)

class Expert(models.Model):
    APPLYING = 'A'
    JUNIOR = 'J'
    SENIOR = 'S'

    EXPERT_STATUS_CHOICES = (
       (APPLYING, 'Expert is applying'),
       (JUNIOR, 'Expert'),
       (SENIOR, 'Senior Expert'),
    )

    AREA_CHOICES = (
       ('US','United States'),
       ('CN','China'),
       ('SG','Singapore'),
       ('JP','Japan'),
       ('OT','Other'),
    )

    INDUSTRY_CHOICES = (
      ("MC",_("Management Consulting")),
      ("EN","Energy"),
      ("HI","Health care and Life Sciences"),
      ("BI","BioPharma"),
      ("ED","Education"),
      ("SE","Semiconductor"),
      ("SW","Software"),
      ("MB","Mobile Internet and Computing"),
      ("DS","Data and Storage"),
      ("VR","VR/AI/Robotics"),
      ("IT","Internet of Things"),
      ("GB","Gaming and Media"),
      ("ET","Entertainment"),
      ("TL","Transport and Logistics"),
      ("AU","Automotive"),
      ("CG","Consumer Goods"),
      ("OT","Other"),
    )

    EXPERTISE_CHOICES = (
      ("ST","Strategy"),
      ("BD","Business Development and Sales"),
      ("SP","Strategic Partnership"),
      ("MK","Marketing"),
      ("MT","Market Research"),
      ("OS","Operations and Supply Chain"),
      ("MA","Merger and Acquisition"),
      ("DA","Data Analytics"),
      ("SE","Software Engineering"),
      ("PJ","Project Management"),
      ("PD","Product Design and Development"),
      ("PM","Product Management"),
      ("EN","Entrepreneurship"),
      ("CC","Cloud Computing"),
      ("AD","Advertisement"),
      ("CL","Corporate Law"),
      ("CF","Corporate Finance"),
      ("AT","Accounting and Taxation"),
      ("OT","Other"),
    )

    ONE_FIVE = 'A'
    FIVE_TEN = 'B'
    TEN_FIFTEEN = 'C'
    LARGER_FIFTEEN = 'D'

    EXPERIENCE_CHOICES = (
       (ONE_FIVE, '1-5 years'),
       (FIVE_TEN, '5-10 years'),
       (TEN_FIFTEEN, '10-15 years'),
       (LARGER_FIFTEEN, '>15 years'),
    )

    AREA_MAPPING = dict((x, y) for x, y in AREA_CHOICES)
    INDUSTRY_MAPPING = dict((x, y) for x, y in INDUSTRY_CHOICES)
    EXPERTISE_MAPPING = dict((x, y) for x, y in EXPERTISE_CHOICES)
    EXPERIENCE_MAPPING = dict((x, y) for x, y in EXPERIENCE_CHOICES)
    EXPERT_STATUS_MAPPING = dict((x, y) for x, y in EXPERT_STATUS_CHOICES)

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    description_text = models.CharField("Description", max_length=500)
    status = models.CharField(max_length=1,
                              choices=EXPERT_STATUS_CHOICES,
                              default=APPLYING)
    area = models.CharField(max_length=2,
                            choices=AREA_CHOICES,
                            default='OT')
    experience = models.CharField(max_length=1,
                                choices=EXPERIENCE_CHOICES,
                                default=ONE_FIVE)
    
    industries = MultiSelectField(max_length=250, 
                                      blank=True, 
                                      choices=INDUSTRY_CHOICES)
    expertise = MultiSelectField(max_length=250, 
                                      blank=True, 
                                      choices=EXPERTISE_CHOICES)
    education = models.CharField(
        max_length=30,
        blank=True
    )

    rating = models.DecimalField(max_digits=3, decimal_places=1, default=0)
    comments_num = models.PositiveIntegerField(default=0)
    
    @classmethod
    def create(cls, form, request=None, **kwargs):
        expert = form.save(commit=False)
        expert.user = kwargs.pop("user", None)
        expert.save()
        return expert

    def has_worked_before(self, user):
      # TODO this method is not efficient
      experts = []
      if user.is_authenticated():
          user_profiles = UserProfile.objects.filter(user=user)
          if user_profiles:
              user_profile = user_profiles[0]
              if user_profile.user_type == 'CLIENT':
                  client = Client.objects.filter(user=user)[0]
                  experts = [project.expert for project in Project.objects.filter(client=client)]
      return self in experts

    @property
    def get_industries(self):
        shortList = (self.industries).split(',')
        return ','.join(str(self.INDUSTRY_MAPPING.get(temp)) for temp in shortList)

    @property
    def get_expertise(self):
        shortList = (self.expertise).split(',')
        return ','.join(str(self.EXPERTISE_MAPPING.get(temp)) for temp in shortList)

    @property
    def get_area(self):
        return self.AREA_MAPPING.get(self.area)

    @property
    def get_experience(self):
        return self.EXPERIENCE_MAPPING.get(self.experience)

    @property
    def get_status(self):
        return self.EXPERT_STATUS_MAPPING.get(self.status)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + "(username:" + self.user.username + ")"

class Project(models.Model):

    INDUSTRY_CHOICES = (
        ("MC",_("Management Consulting")),
        ("EN","Energy"),
        ("HI","Health care and Life Sciences"),
        ("BI","BioPharma"),
        ("ED","Education"),
        ("SE","Semiconductor"),
        ("SW","Software"),
        ("MB","Mobile Internet and Computing"),
        ("DS","Data and Storage"),
        ("VR","VR/AI/Robotics"),
        ("IT","Internet of Things"),
        ("GB","Gaming and Media"),
        ("ET","Entertainment"),
        ("TL","Transport and Logistics"),
        ("AU","Automotive"),
        ("CG","Consumer Goods"),

src/search/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormMixin
from django.utils import timezone

from common.models import Expert, UserProfile, Client, Project

class ExpertDetailView(DetailView):

    model = Expert

    def get_context_data(self, **kwargs):
        context = super(ExpertDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class ExpertListView(ListView):

    model = Expert
    paginate_by = 10
    context_object_name = "expert_list"

    def get_queryset(self):
        return_set = Expert.objects.all()
        if self.request.method == 'GET' and 'industry' in self.request.GET:
            industry_val = self.request.GET['industry']
            if industry_val != 'ALL':
              return_set = return_set.filter(industries__icontains=industry_val)
        if self.request.method == 'GET' and 'expertise' in self.request.GET:
            expertise_val = self.request.GET['expertise']
            if expertise_val != 'ALL':
              return_set = return_set.filter(expertise__icontains=expertise_val)
        if self.request.method == 'GET' and 'experience' in self.request.GET:
            experience_val = self.request.GET['experience']
            if experience_val != 'ALL':
              return_set = return_set.filter(experience=experience_val)
        if self.request.method == 'GET' and 'area' in self.request.GET:
            area_val = self.request.GET['area']
            if area_val != 'ALL':
              return_set = return_set.filter(area=area_val)
        return return_set

    def get_context_data(self, **kwargs):
        context = super(ExpertListView, self).get_context_data(**kwargs)
        # TODO this is not efficient. Need to optimize.
        can_views = []
        user = self.request.user
        if self.request.user.is_authenticated():
            user_profiles = UserProfile.objects.filter(user=user)
            if user_profiles:
                user_profile = user_profiles[0]
                if user_profile.user_type == 'CLIENT':
                    client = Client.objects.filter(user=user)[0]
                    can_views = [project.expert.id for project in Project.objects.filter(client=client)]
        context['now'] = timezone.now()
        context['can_views'] = can_views
        return context

#def filter(request):

#def index(request):
#    context = RequestContext(request, {
#        'latest_question_list': 'sss',
#    })
#    return render(request, 'consultants/index.html', context)

src/search/templates/common/expert_detail.html
<h1>{{ object.user.first_name }} {{ object.user.last_name }}</h1>
<!--<h1>{{ object.last_name_text }}</h1> -->
<p>{% trans "Description"% }: {{ object.description_text }}</p>
<p>{% trans "Industry" %}: {{ object.industry }}</p>
<p>{% trans "Expertise" %}: {{ object.expertise }}</p>
<p>{% trans "Experience" %}: {{ object.experience }}</p>
<p>{% trans "Status" %}: {{ object.status }}</p>
<p>{% trans "Area" %}: {{ object.area }}</p>

src/search/templates/common/expert_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load expert_tags %}

{% block content %}

<style>

 h3 {
  font: bold 20px/1.5 Helvetica, Verdana, sans-serif;
}

 li img {
  float: left;
  margin: 0 15px 0 0;
}

 li p {
  font: 1000 12px/1.5 Georgia, Times New Roman, serif;
}

 li {
  padding: 10px;
  overflow: auto;
}

 .expert-list:hover {
  background: #eee;
  cursor: pointer;
}
</style>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">




      <h2>{% trans "Invite Experts to a Project" %}</h2>
      <form action="{% url 'search:expert-list' %}" method="GET">{% csrf_token %}
      <div class="row">
        <div class="col-sm-2">
          <h5>{% trans "Industry" %}</h5>
        </div>
        <div class="col-sm-10">
          <select name="industry" class="form-control">
            <option id="industryALL" value="ALL">{% trans "All" %}</option>
            <option id="industryMC" value="MC">{% trans "Management Consulting" %}</option>
            <option id="industryEN" value="EN">{% trans "Energy" %}</option>
            <option id="industryHI" value="HI">{% trans "Health care and Life Sciences" %}</option>
            <option id="industryBI" value="BI">{% trans "BioPharma" %}</option>
            <option id="industryED" value="ED">{% trans "Education" %}</option>
            <option id="industrySE" value="SE">{% trans "Semiconductor" %}</option>
            <option id="industrySW" value="SW">{% trans "Software" %}</option>
            <option id="industryMB" value="MB">{% trans "Mobile Internet and Computing" %}</option>
            <option id="industryDS" value="DS">{% trans "Data and Storage" %}</option>
            <option id="industryVR" value="VR">{% trans "VR/AI/Robotics" %}</option>
            <option id="industryIT" value="IT">{% trans "Internet of Things" %}</option>
            <option id="industryGB" value="GB">{% trans "Gaming and Media" %}</option>
            <option id="industryET" value="ET">{% trans "Entertainment" %}</option>
            <option id="industryTL" value="TL">{% trans "Transport and Logistics" %}</option>
            <option id="industryAU" value="AU">{% trans "Automotive" %}</option>
            <option id="industryCG" value="CG">{% trans "Consumer Goods" %}</option>
            <option id="industryOT" value="OT">{% trans "Others" %}</option>
          </select>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2">
          <h5>{% trans "Expertise" %}</h5>
        </div>
        <div class="col-sm-10">
          <select name="expertise" class="form-control">
            <option id="expertiseALL" value="ALL">{% trans "All" %}</option>
            <option id="expertiseST" value="ST">{% trans "Strategy" %}</option>
            <option id="expertiseBD" value="BD">{% trans "Business Development and Sales" %}</option>
            <option id="expertiseSP" value="SP">{% trans "Strategic Partnership" %}</option>
            <option id="expertiseMK" value="MK">{% trans "Marketing" %}</option>
            <option id="expertiseMT" value="MT">{% trans "Market Research" %}</option>
            <option id="expertiseOS" value="OS">{% trans "Operations and Supply Chain" %}</option>
            <option id="expertiseMA" value="MA">{% trans "Merger and Acquisition" %}</option>
            <option id="expertiseDA" value="DA">{% trans "Data Analytics" %}</option>
            <option id="expertiseSE" value="SE">{% trans "Software Engineering" %}</option>
            <option id="expertisePJ" value="PJ">{% trans "Project Management" %}</option>
            <option id="expertisePD" value="PD">{% trans "Product Design and Development" %}</option>
            <option id="expertisePM" value="PM">{% trans "Product Management" %}</option>
            <option id="expertiseEN" value="EN">{% trans "Entrepreneurship" %}</option>
            <option id="expertiseCC" value="CC">{% trans "Cloud Computing" %}</option>
            <option id="expertiseAD" value="AD">{% trans "Advertisement" %}</option>
            <option id="expertiseCL" value="CL">{% trans "Corporate Law" %}</option>
            <option id="expertiseCF" value="CF">{% trans "Corporate Finance" %}</option>
            <option id="expertiseAT" value="AT">{% trans "Accounting and Taxation" %}</option>
            <option id="expertiseOT" value="OT">{% trans "Others" %}</option>
          </select>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2">
          <h5>{% trans "Experience" %}</h5>
        </div>
        <div class="col-sm-10">
          <select name="experience" class="form-control">
            <option id="experienceALL" value="ALL">{% trans "All" %}</option>
            <option id="experienceA" value="A">{% trans "1-5 years" %}</option>
            <option id="experienceB" value="B">{% trans "5-10 years" %}</option>
            <option id="experienceC" value="C">{% trans "10-15 years" %}</option>
            <option id="experienceD" value="D">{% trans " >15 years" %}</option>
          </select>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2">
          <h5>{% trans "Area" %}</h5>
        </div>
        <div class="col-sm-10">
          <select name="area" class="form-control">
            <option id="areaALL" value="ALL">{% trans "All" %}</option>
            <option id="areaUS" value="US">{% trans "United States" %}</option>
            <option id="areaCN" value="CN">{% trans "China" %}</option>
            <option id="areaSN" value="SN">{% trans "Singapore" %}</option>
            <option id="areaJP" value="JP">{% trans "Japan" %}</option>
            <option id="areaOT" value="OT">{% trans "Other" %}</option>
          </select>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-sm-12">
          <br>
          <button class="pure-button pure-button-primary" type="submit" value="Submit" > Search </button>
        </div>
      </div>
      <script>
      function getQueryVariable(variable)
      {
             var query = window.location.search.substring(1);
             var vars = query.split("&");
             for (var i=0;i<vars.length;i++) {
                     var pair = vars[i].split("=");
                     if(pair[0] == variable){return pair[1];}
             }
             return(false);
      }

      function setSelectedIndex(s)
      {
        s.selected = true;
        return;
      }
      var strIndustryName = "industry";
      var strIndustryVal = getQueryVariable("industry");
      var strIndustryConcat = strIndustryName.concat(strIndustryVal);

      var strExpertiseName = "expertise";
      var strExpertiseVal = getQueryVariable("expertise");
      var strExpertiseConcat = strExpertiseName.concat(strExpertiseVal);

      var strExperienceName = "experience";
      var strExperienceVal = getQueryVariable("experience");
      var strExperienceConcat = strExperienceName.concat(strExperienceVal);

      var strAreaName = "area";
      var strAreaVal = getQueryVariable("area");
      var strAreaConcat = strAreaName.concat(strAreaVal);

      setSelectedIndex(document.getElementById(strIndustryConcat));
      setSelectedIndex(document.getElementById(strExpertiseConcat));
      setSelectedIndex(document.getElementById(strExperienceConcat));
      setSelectedIndex(document.getElementById(strAreaConcat));
      </script>

      <br>
      <br>
      <div class="col-sm-12">
      <br>
      <br>
      {% if expert_list %}
        <div class="row">
          <div class="col-sm-12">
            {% for expert in expert_list %}
            <div class="row expert-list">
              <a href="/profile/{{ expert.user.username }}">
              <div class="col-sm-3 col-xs-4">
                {% if expert.id in can_views %}
                <img src="/media/{{ expert.user.username }}.jpg" style="width:100%" onerror="this.src='{% static '/images/empty_headshot.jpg' %}';" />
                {% else %}
                <img src="/static/images/empty_headshot.jpg" style="width:100%" onerror="this.src='{% static '/images/empty_headshot.jpg' %}';" />
                {% endif %}
              </div>
              </a>
              <div class="col-sm-9 col-sm-8">
                <h3>
                  <a href="/profile/{{ expert.user.username }}">{{ expert.user }}</a>
                </h3>
                {% if expert.rating != 0 %}
                <div style="margin-top:-0.8em">
                  <p class='text-muted'><img src="{% static '/images/rating/star_' %}{{ expert.rating | half_round_rating}}.gif"/>&nbsp {{ expert.comments_num}} reviews</p>
                </div>
                {% endif %}
                <p>{{ expert.description_text}}</p>
                <p>{{ expert.email}}</p>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
          {% if is_paginated %}
              <div class="pagination" >
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <ul class="pager">
                          <a id="prePage" href="?page={{ page_obj.previous_page_number }}">previous</a>
                          </ul>
                          <script>
                           var prePage = document.getElementById("prePage");
                           var originalString = prePage.getAttribute("href");
                           if(getQueryVariable("industry") != false)
                           {
                             var concatStr = originalString.concat(
                               "&industry=",getQueryVariable("industry"),
                               "&expertise=",getQueryVariable("expertise"),
                               "&experience=",getQueryVariable("experience"),
                               "&area=",getQueryVariable("area"));
                             prePage.setAttribute("href", concatStr);
                           }
                          </script>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <ul class="pager">
                          <a id="nextPage" href="?page={{ page_obj.next_page_number }}">next</a>
                          </ul>
                          <script>
                           var prePage = document.getElementById("nextPage");
                           var originalString = prePage.getAttribute("href");
                           if(getQueryVariable("industry") != false)
                           {
                             var concatStr = originalString.concat(
                               "&industry=",getQueryVariable("industry"),
                               "&expertise=",getQueryVariable("expertise"),
                               "&experience=",getQueryVariable("experience"),
                               "&area=",getQueryVariable("area"));
                             prePage.setAttribute("href", concatStr);
                           }
                          </script>
                      {% endif %}
                  </span>
              </div>
          {% endif %}
      {% else %}
          <h3>{% trans "Experts" %}</h3>
          <p>{% trans "No experts found in this area, please change search condition" %}</p>
      {% endif %}
      </div>


    </div>
  </div>
</div> <!-- for Container -->
{% endblock %}